language: python

python:
  - "3.8.7"

cache:
  directories:
    - $HOME/stanza_resources/
    - $HOME/cltk_data/
    - $HOME/.cache/pip

before_install:
  - python -m pip install --upgrade pip

install:
  - pip install --user -r requirements.txt --use-feature=2020-resolver

script:
  - pytest --doctest-modules --cov-report=term --mypy --cov-config=.coveragerc --pylint -vv --cov=mlyoucanuse
